name: Build product

on:
  pull_request:

permissions:
  id-token: write

# Can we use matrix job for build?
#   I dropped off this idea because of job dependecies.
#   But why dependencies could be important for build? => Only if refresh is done and next layer refer to attribute changed during refresh. I got a little bit accurate plan.
#   But without dependencies I speed up build. Speed here is more important. Plan is in any case is not 100% accurate here.
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        layer: ["base", "mgmt", "core", "k8s"]
    secrets: inherit
    uses: ./.github/workflows/_build_layer.yml
    with:
      layer: ${{ matrix.layer }}
      environment: "dev"
