name: Deploy product

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  deploy_dev:
    secrets: inherit
    uses: ./.github/workflows/_deploy_env.yml
    with:
      environment: dev